apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    app.kubernetes.io/part-of: edc-translation
    edc-translation.io/operator-surface: cnpg
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/part-of: edc-translation
    edc-translation.io/operator-surface: strimzi
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    app.kubernetes.io/part-of: edc-translation
    edc-translation.io/operator-surface: keda
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/part-of: edc-translation
    edc-translation.io/operator-surface: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/part-of: edc-translation
    edc-translation.io/operator-surface: ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: edc-translation
    edc-translation.io/operator-surface: monitoring
