apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edc-translation
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: edc-translation
      server: https://kubernetes.default.svc
    - namespace: edc-translation-staging
      server: https://kubernetes.default.svc
    - namespace: cnpg-system
      server: https://kubernetes.default.svc
    - namespace: kafka
      server: https://kubernetes.default.svc
    - namespace: keda
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
